### ISSUE TITLE
Cannot connect to UGE600 

### ISSUE THREAD

**Issue by imihailovs** [jvitkauskas/homeassistant_salus#43]
I am trying to add UGE600 gateway via HACS installed component and I can't seem to connect to the gateway - tried both real and all-zero EUIDs. 

I've made sure to maintain Local WIFI setting and I've also tried connecting via Ethernet and WIFI connections one after another - no success - I'm getting "Invalid IP address. Try again." error message. 

Is there a log file somewhere that I can use to analyze the response from the GW?

**Comment by alex-ricobon** [comment]
same issue here, did you manage to fix it?

**Comment by stvogel** [comment]
I have the same problem for the UGE600.
In the log I find:
```
2023-10-25 09:48:07.134 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyit600/gateway.py", line 929, in _make_encrypted_request
    response_json_string = self._encryptor.decrypt(response_bytes)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyit600/encryptor.py", line 27, in decrypt
    plain: bytes = unpadder.update(padded_data) + unpadder.finalize()
                                                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/padding.py", line 160, in finalize
    result = _byte_unpadding_check(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/padding.py", line 102, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/salus/config_flow.py", line 44, in async_step_user
    unique_id = await gateway.connect()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyit600/gateway.py", line 101, in connect
    all_devices = await self._make_encrypted_request(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyit600/gateway.py", line 957, in _make_encrypted_request
    raise IT600CommandError(
pyit600.exceptions.IT600CommandError: Unknown error occurred while communicating with iT600 gateway
```
Seems to me as if this is a problem of the underlying pyit600 -library, https://github.com/jvitkauskas/pyit600

**Comment by andvarga79** [comment]
Hi All,
I just purchased a Salus IT600 underfloor heating automatization, hoping to integrate it in Home Assistant, and I am at the point that I will send it back if not doable.
I have downloaded latest of the integration from HACS and when I try to add IP and EUID the error of Failed to connect, please check IP address coms back. I have tried the troubleshooting from the readme, all looks good, but error persists.
I am not an IT person, and not really understanding the above solution.
Do you mind creating a tutorial as for a person without required IT knowledge? Thank you!

**Comment by nicu-cbn** [comment]
Hello. I have the same error.
Also found in the HA logs the following:

Logger: pyit600
Source: custom_components/salus/config_flow.py:44
Integration: Salus iT600 ([documentation](https://github.com/jvitkauskas/homeassistant_salus), [issues](https://github.com/jvitkauskas/homeassistant_salus/issues))
First occurred: 00:47:29 (1 occurrences)
Last logged: 00:47:29

Timeout while connecting to gateway:

**Comment by palladin8282** [comment]
Hi, 
I have simmilar issue, 

But what I found also is that:

Also check if you have "Local Wifi Mode" enabled:

Open Smart Home app on your phone
Sign in
Double tap your Gateway to open info screen
Press gear icon to enter configuration
Scroll down a bit and check if "Disable Local WiFi Mode" is set to "No"
Scroll all the way down and save settings
Restart Gateway by unplugging/plugging USB power

In my gateway this mode was disabled

Trying this righ now - I will inform about results.

**Comment by palladin8282** [comment]
Hi All, 
After enabling the Local Wifi Mode to on and restarting the gateway I was able to establish connection :) 
Maybe this will help you too.

**Comment by nicu-cbn** [comment]
On my side my router has an option to isolate IoT devices and Salus Gateway was one of those isolated devices, that's why Home Assistant was unable to connect. 
Solving this was fixed my issue

**Comment by imihailovs** [comment]
Came back to integrating the Gateway, but still facing the same issue. Both HA and Gateway are on the same subnet, firewall doesn't block anything. Local mode is enabled on the gateway.
What I have noticed is that I can't ping the IP address of a gateway. Could be normal, don't know.
Anyhow, the error I am getting from the logs is as follows:

`This error originated from a custom integration.

Logger: pyit600
Source: custom_components/salus/config_flow.py:44
integration: Salus iT600 (documentation, issues)
First occurred: 9:21:30 AM (7 occurrences)
Last logged: 9:29:17 AM

Timeout while connecting to gateway:`

**Comment by rexopl** [comment]
Wow thanks @stvogel using `0000000000000000` works! o.O

**Comment by bjorn-lebel** [comment]
Hi, i have the same issue as @imihailovs,
The UG600 are connected and it works in the app, with equipment connected all through, that i can control through the app.

However I cant register the gateway with HA...

It looks like i am stuck in between, 
if I reset the gateway completely and connect to it in the offline mode I can access a webserver on the wifi side of the gateway (even if that webserver says 404...), so far it looks promising...

However if i instead connect the LAN, and it is registered to the internet, 
it goes into "darkmode" and dont respond to anything, 
either on the LAN side or on the wifi side with a configured SSID.
I can see the IPs and MAC addresses on my firewall but the UG600 doesnt respond to anything!

I am leaning to that a firmware update closed the access when connected to the internet.

I have factory reset it like 20 times by now and whatever I do I come back to the same state, where Local WiFi Access are enabled but doesnt respond (in either working mode).

TBH and warn others, I will return it and buy another system!

**Comment by DanielKarwacki** [comment]
With my integration I had the `Invalid padding bytes.` error as well. The solution was to use `0000000000000000` as EUID instead the one taken from the sticker on UGE600 device.

@epoplavskis I believe that information (try with `0000000000000000`) in plugin README.md could save people lifes :) What do you think?
